name: CI Docker build

on:
  push:
    branches: ["main"]
  release:
    types: [created]

jobs:
  build:
    name: Cria imagens e faz deploy HML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repo git
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Staging
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: madalozzo/icecast2:staging

      - name: Build Release
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: madalozzo/icecast2:latest
